Repository IC-H/12th_OPEN_SW_DEV_CONF, pull requests merged in 2018-09, with the labels that each got.

#33 【공통 모델】임포트 용의 하게 하기 위한 수정
  mysite/common/models/__init__.py
Labels: enhancement

#32 【URL 등록 화면】 뷰 작성
  mysite/common/templates/common/accordion.html
  mysite/common/templates/common/element/hidden_input.html
  mysite/static/style/common.css
  mysite/user/templates/user/url/register.html
  mysite/user/url/__init__.py
  mysite/user/url/views.py
  mysite/user/urls.py
Labels: enhancement

#31 【URL 검색화면】 View Class 적용 & 검색 JS 처리 수정
  mysite/common/models/domain_url.py
  mysite/notice_url/templates/search/index.html
  mysite/notice_url/urls.py
  mysite/notice_url/views.py
  mysite/static/js/notice_url/notice_url.js
Labels: enhancement

#36 【URL 검색 화면】모델의 임포트 패스 수정
  mysite/notice_url/ajax.py
  mysite/notice_url/views.py
Labels: enhancement

#35 【URL 등록화면】뷰 컨드롤러
  mysite/common/models/domain_url.py
  mysite/common/models/user_url.py
  mysite/user/url/views.py
Labels: enhancement

#37 [User 로그인창]
  mysite/common/models/user.py
  mysite/common/models/user_url.py
  mysite/user/admin.py
  mysite/user/auth.py
  mysite/user/forms.py
  mysite/user/signals.py
  mysite/user/templates/user/sign_in.html
  mysite/user/templates/user/sign_up.html
  mysite/user/urls.py
  mysite/user/views.py
Labels: enhancement

#42 【URL 등록 API】작성
  mysite/api/urls.py
  mysite/api/user/__init__.py
  mysite/api/user/controller.py
  mysite/api/user/urls.py
  mysite/common/templates/common/base.html
  mysite/common/templates/common/element/flash_messages.html
  mysite/static/style/common.css
Labels: enhancement

#44 【URL 등록 화면】URL 중복 수정
  mysite/user/url/urls.py
Labels: bug

#47 [User 세션관리] 로그인 후 세션 저장
  mysite/api/user/controller.py
  mysite/user/auth.py
  mysite/user/url/views.py
Labels: enhancement

#51 [Secret Key] 시크릿키 제거
  mysite/mysite/settings/base.py
Labels: enhancement

#50 【DOC】도메인에서 이동 가능한 유알엘 추출 로직
  doc/logic/uml/get_next_url_list.uml
Labels: manage

#52 【COMMON MODEL】공통 HTML VECTOR 모델 추가
  mysite/common/models/__init__.py
  mysite/common/models/en_word.py
  mysite/common/models/html_vector.py
  mysite/common/models/ko_word.py
  mysite/common/models/lang_mst.py
  mysite/common/models/tag.py
  mysite/common/models/word.py
Labels: enhancement

#53 #39 【Log In】key_salt값을 settings에서 불러오도록 수정
  mysite/common/models/user.py
Labels: enhancement

#60 【COMMON MODEL】공통 HTML VECTOR 테이블 구조 확정
  mysite/common/models/__init__.py
  mysite/common/models/domain_url.py
  mysite/common/models/en_word.py
  mysite/common/models/html_vector.py
  mysite/common/models/ko_word.py
  mysite/common/models/word.py
Labels: enhancement

#61 raw note for crawler
  README.md
Labels: manage

#62 #46 【백 엔드】【쉘】 vectorize
  mysite/batch/__init__.py
  mysite/batch/admin.py
  mysite/batch/apps.py
  mysite/batch/migrations/__init__.py
  mysite/batch/models.py
  mysite/batch/tests.py
  mysite/batch/vectorize/__init__.py
  mysite/batch/vectorize/base_vectorize.py
  mysite/batch/vectorize/html_vectorize.py
  mysite/batch/views.py
  mysite/mysite/settings/base.py
Labels: enhancement

#63 #26 도메인에서 공지사항 일람 URL을 찾는 쉘
  mysite/batch/crawler/__init__.py
  mysite/batch/crawler/base_crawler.py
Labels: enhancement

#67 WIP: #46 【백 엔드】【쉘】 Converter
  mysite/batch/model_converter/__init__.py
  mysite/batch/model_converter/base_converter.py
  mysite/common/models/domain_mst.py
  mysite/common/models/domain_url.py
Labels: enhancement

#69 Update README.md
  README.md
Labels: manage

#68 #65 【백 엔드】【쉘】커멘드 상에서 실행 가능한 함수 작성
  mysite/batch/management/__init__.py
  mysite/batch/management/commands/__init__.py
  mysite/batch/management/commands/search_notice_url.py
Labels: enhancement

#71 [SHELL 이메일알람] 유저에게 이메일 알람
  mysite/batch/mail/__init__.py
  mysite/batch/mail/mailer.py
  mysite/batch/management/commands/send_mail.py
Labels: enhancement

#70 #46 【백 엔드】【쉘】 model convert
  mysite/batch/model_converter/__init__.py
  mysite/batch/model_converter/html_model_converter.py
  mysite/common/models/lang_mst.py
  mysite/common/models/tag.py
  mysite/common/models/word.py
Labels: enhancement

#78 【SHELL 벡터 비교】비교 함수 작성
  mysite/batch/compare_vector/__init__.py
  mysite/batch/compare_vector/compare.py
  mysite/batch/crawler/__init__.py
  mysite/batch/crawler/notice_crawler.py
  mysite/batch/management/commands/compare_vector.py
  mysite/batch/vectorize/base_vectorize.py
  mysite/common/models/html_vector.py
Labels: enhancement

#80 #49 【백 엔드】【쉘】한 URL에서 이동할 수 있는 URL 리스트 특정 하는 기능
  mysite/batch/crawler/__init__.py
  mysite/batch/crawler/notice_url_crawler.py
  mysite/batch/management/commands/search_notice_url.py
  mysite/batch/model_converter/base_converter.py
  mysite/batch/navigator/__init__.py
  mysite/batch/navigator/base_container.py
  mysite/batch/navigator/item.py
  mysite/batch/navigator/navigation_book.py
  mysite/batch/navigator/navigator.py
  mysite/batch/vectorize/base_vectorize.py
  mysite/common/utils/__init__.py
  mysite/common/utils/response_related_utils.py
Labels: enhancement

#83 #57 【백 엔드】【학습】 학습 개발
  mysite/common/utils/__init__.py
  mysite/common/utils/vector_utils.py
Labels: enhancement

#84 [SHELL 벡터 비교] vectorize클래스 reset 조정
  mysite/batch/compare_vector/compare.py
Labels: bug, enhancement

#86 for learning
  README.md
Labels: manage

#90 【백 엔드】【공지사항 유알엘 검색 쉘】 keywords argument 대응
  mysite/batch/crawler/notice_url_crawler.py
Labels: bug

#91 【백 엔드】【학습】 학습 개발
  mysite/batch/learning/__init__.py
  mysite/batch/learning/base_classifier.py
  mysite/batch/management/commands/learn_by_svm.py
Labels: enhancement

#93 Feature/learning
  mysite/batch/learning/__init__.py
  mysite/batch/learning/deep_learning.py
  mysite/batch/management/commands/deep_learning.py
Labels: enhancement

#92 For Debugging
  mysite/batch/compare_vector/compare.py
  mysite/batch/crawler/notice_crawler.py
  mysite/batch/crawler/notice_url_crawler.py
  mysite/batch/management/commands/compare_vector.py
  mysite/batch/management/commands/search_notice_url.py
  mysite/batch/navigator/navigator.py
Labels: enhancement

#94 rename classifier
  mysite/batch/learning/__init__.py
  mysite/batch/learning/deep_learning_classifier.py
  mysite/batch/learning/svm_classifier.py
  mysite/batch/management/commands/learn_by_svm.py
Labels: enhancement

#95 Update README.md
  README.md
Labels: enhancement

#96 [SHELL Classifier] Base모델 생성
  mysite/batch/learning/__init__.py
  mysite/batch/learning/base_classifier.py
  mysite/batch/learning/deep_learning_classifier.py
  mysite/batch/learning/svm_classifier.py
  mysite/batch/management/commands/deep_learning.py
Labels: enhancement

#98 인덴트 수정
  mysite/api/urls.py
  mysite/batch/learning/base_classifier.py
  mysite/batch/mail/mailer.py
  mysite/batch/management/commands/deep_learning.py
  mysite/batch/management/commands/send_mail.py
Labels: bug

#99 【백 엔드】【학습】 학습 개발
  mysite/common/utils/response_related_utils.py
Labels: enhancement

#100 [코드수정] 테스트 코드 제거
  mysite/batch/compare_vector/compare.py
  mysite/batch/crawler/notice_crawler.py
  mysite/batch/crawler/notice_url_crawler.py
  mysite/batch/management/commands/deep_learning.py
Labels: enhancement
