Repository IC-H/12th_OPEN_SW_DEV_CONF, pull requests merged in 2018-10, with the labels that each got.

#103 【벡 엔드】【학습】학습결과를 저장 불러오는 기능 추가
  .gitignore
  mysite/batch/learning/base_classifier.py
  mysite/batch/learning/deep_learning_classifier.py
  mysite/batch/learning/svm_classifier.py
Labels: enhancement

#104 【Data Maker】【학습】
  mysite/batch/learning/__init__.py
  mysite/batch/learning/data_maker/__init__.py
  mysite/batch/learning/data_maker/base_data_maker.py
  mysite/batch/learning/data_maker/notice_url_data_maker.py
  mysite/batch/learning/learning_data_maker.py
  mysite/batch/management/commands/make_data.py
Labels: enhancement

#106 【DOC】도메인에서 이동 가능한 유알엘 추출 로직 수정
  doc/logic/uml/get_next_url_list.uml
Labels: manage

#109 reverting deep learning classifier
  mysite/batch/learning/deep_learning_classifier.py
  mysite/batch/management/commands/deep_learning.py
Labels: bug

#110 【벡 엔드】【학습】SVM classifier
  mysite/batch/learning/svm_classifier.py
  mysite/batch/management/commands/learn_by_svm.py
Labels: enhancement

#111 【벡 엔드】【Notice Url Searcher】
  mysite/batch/crawler/notice_url_crawler.py
Labels: enhancement

#118 #66 【버그】【프론트】【URL Register API】Request Method 체크 추가
  mysite/api/user/controller.py
Labels: bug

#119 #79 【Timeout】크롤링시 타임아웃 처리
  mysite/batch/crawler/notice_url_crawler.py
Labels: bug

#120 [프론트] 로그아웃 및 회원탈퇴 구현
  mysite/notice_url/templates/search/index.html
  mysite/static/style/common.css
  mysite/user/auth.py
  mysite/user/templates/user/check_delete.html
  mysite/user/templates/user/delete.html
  mysite/user/templates/user/log_out.html
  mysite/user/templates/user/sign_in.html
  mysite/user/templates/user/sign_up.html
  mysite/user/templates/user/url/list.html
  mysite/user/url/views.py
  mysite/user/urls.py
  mysite/user/views.py
Labels: bug
